//! Deterministic rendering of env files + systemd units from a parsed [`SiteConfig`].
//!
//! Determinism: a fixed key order, no timestamps/host data beyond config, identical bytes for
//! identical input. systemd path directives (`EnvironmentFile`, `ReadOnlyPaths`, the `ExecStart`
//! binary) are ABSOLUTE literals (systemd does not expand env vars there); only `ExecStart`
//! arguments use `${VAR}` (which systemd does expand).

use std::path::Path;

use jurisearch_embed::EmbeddingProvider;

use crate::bind::{BindAddress, TcpExposure, parse_bind};
use crate::config::SiteConfig;
use crate::error::DeployError;
use crate::secret;

const GENERATED_HEADER: &str =
    "# Generated by `jurisearchctl site render` from site.toml. DO NOT EDIT — regenerate instead.";

/// The full set of files rendered from one [`SiteConfig`].
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct RenderedSite {
    pub site_env: String,
    pub syncd_env: String,
    pub bge_m3_env: String,
    pub site_unit: String,
    pub syncd_unit: String,
    pub bge_m3_unit: String,
}

/// A single rendered output file: its relative path under the render root, its bytes, and whether it
/// is secret (env files: `0600`) or a public unit (`0644`).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct RenderedFile {
    pub relative_path: &'static str,
    pub contents: String,
    pub secret: bool,
}

impl RenderedSite {
    /// The six rendered files in a stable order, with their target-relative paths and sensitivity.
    #[must_use]
    pub fn files(&self) -> Vec<RenderedFile> {
        vec![
            RenderedFile {
                relative_path: "generated/site.env",
                contents: self.site_env.clone(),
                secret: true,
            },
            RenderedFile {
                relative_path: "generated/syncd.env",
                contents: self.syncd_env.clone(),
                secret: true,
            },
            RenderedFile {
                relative_path: "generated/bge-m3.env",
                contents: self.bge_m3_env.clone(),
                secret: true,
            },
            RenderedFile {
                relative_path: "systemd/jurisearch-site.service",
                contents: self.site_unit.clone(),
                secret: false,
            },
            RenderedFile {
                relative_path: "systemd/jurisearch-syncd.service",
                contents: self.syncd_unit.clone(),
                secret: false,
            },
            RenderedFile {
                relative_path: "systemd/jurisearch-bge-m3.service",
                contents: self.bge_m3_unit.clone(),
                secret: false,
            },
        ]
    }

    /// Write all six files under `root`: env files `0600`, units `0644`. Creates `generated/` and
    /// `systemd/` subdirectories.
    pub fn write_to(&self, root: &Path) -> Result<(), DeployError> {
        for subdir in ["generated", "systemd"] {
            let dir = root.join(subdir);
            std::fs::create_dir_all(&dir).map_err(|source| DeployError::Write {
                path: dir.clone(),
                source,
            })?;
        }
        for file in self.files() {
            let path = root.join(file.relative_path);
            let result = if file.secret {
                secret::write_secret_file(&path, file.contents.as_bytes())
            } else {
                secret::write_file_with_mode(&path, file.contents.as_bytes(), 0o644)
            };
            result.map_err(|source| DeployError::Write { path, source })?;
        }
        Ok(())
    }
}

impl SiteConfig {
    /// Render the env files + systemd units. Fails only if `site.bind` cannot be parsed (validation,
    /// which the caller should run first, catches that and every other policy problem).
    pub fn render(&self) -> Result<RenderedSite, DeployError> {
        let bind = parse_bind(&self.site.bind).map_err(|error| {
            let mut errors = crate::error::ValidationErrors::default();
            errors.push(
                "site.bind.malformed",
                format!("site.bind `{}` is invalid: {error}", self.site.bind),
                "use `tcp://host:port` or `unix:///absolute/path`",
            );
            DeployError::Validation(errors)
        })?;

        Ok(RenderedSite {
            site_env: self.render_site_env(&bind),
            syncd_env: self.render_syncd_env(),
            bge_m3_env: self.render_bge_m3_env(),
            site_unit: self.render_site_unit(&bind),
            syncd_unit: self.render_syncd_unit(),
            bge_m3_unit: self.render_bge_m3_unit(),
        })
    }

    fn env_file_path(&self, name: &str) -> String {
        self.system
            .config_dir
            .join("generated")
            .join(name)
            .display()
            .to_string()
    }

    fn render_site_env(&self, bind: &BindAddress) -> String {
        let bind_value = match bind {
            BindAddress::Tcp { host_port, .. } => host_port.clone(),
            BindAddress::Unix { path } => path.clone(),
        };
        let embedder = &self.embedder;
        let mut out = String::new();
        out.push_str(GENERATED_HEADER);
        out.push('\n');
        push_env(&mut out, "JURISEARCH_SITE_BIND", &bind_value);
        push_env(
            &mut out,
            "JURISEARCH_SITE_WORKERS",
            &self.site.workers.to_string(),
        );
        push_env(&mut out, "JURISEARCH_DB_HOST", &self.database.host);
        push_env(
            &mut out,
            "JURISEARCH_DB_PORT",
            &self.database.port.to_string(),
        );
        push_env(&mut out, "JURISEARCH_DB_NAME", &self.database.name);
        push_env(&mut out, "JURISEARCH_READ_USER", &self.database.read_user);
        push_env(
            &mut out,
            "JURISEARCH_EMBED_PROVIDER",
            provider_str(embedder.provider),
        );
        push_env(&mut out, "JURISEARCH_EMBED_BASE_URL", &embedder.base_url);
        push_env(&mut out, "JURISEARCH_EMBED_MODEL", &embedder.model_name);
        push_env(
            &mut out,
            "JURISEARCH_EMBED_DIMENSION",
            &embedder.dimension.to_string(),
        );
        push_env(
            &mut out,
            "JURISEARCH_EMBED_NORMALIZE",
            &embedder.normalize.to_string(),
        );
        push_env(&mut out, "JURISEARCH_EMBED_POOLING", &embedder.pooling);
        push_env(
            &mut out,
            "JURISEARCH_EMBED_TOKENIZER_JSON",
            &embedder.tokenizer_json.display().to_string(),
        );
        out
    }

    fn render_syncd_env(&self) -> String {
        let mut out = String::new();
        out.push_str(GENERATED_HEADER);
        out.push('\n');
        push_env(&mut out, "JURISEARCH_DB_HOST", &self.database.host);
        push_env(
            &mut out,
            "JURISEARCH_DB_PORT",
            &self.database.port.to_string(),
        );
        push_env(&mut out, "JURISEARCH_DB_NAME", &self.database.name);
        push_env(
            &mut out,
            "JURISEARCH_WRITER_USER",
            &self.database.writer_user,
        );
        push_env(&mut out, "JURISEARCH_READ_USER", &self.database.read_user);
        push_env(&mut out, "JURISEARCH_OWNER_ROLE", &self.database.owner_role);
        push_env(
            &mut out,
            "JURISEARCH_SOURCE_ROOT",
            &self.sync.source_root.display().to_string(),
        );
        push_env(
            &mut out,
            "JURISEARCH_INTERVAL_SECS",
            &self.sync.interval_secs.to_string(),
        );
        out
    }

    fn render_bge_m3_env(&self) -> String {
        let embedder = &self.embedder;
        let mut out = String::new();
        out.push_str(GENERATED_HEADER);
        out.push('\n');
        push_env(
            &mut out,
            "JURISEARCH_BGE_M3_MODEL",
            &embedder.model_path.display().to_string(),
        );
        push_env(
            &mut out,
            "JURISEARCH_BGE_M3_PORT",
            &embedder.port.to_string(),
        );
        push_env(&mut out, "JURISEARCH_BGE_M3_POOLING", &embedder.pooling);
        out
    }

    fn render_site_unit(&self, bind: &BindAddress) -> String {
        let jurisearch_bin = self
            .system
            .install_dir
            .join("jurisearch")
            .display()
            .to_string();
        let mut exec = vec![format!("{jurisearch_bin} serve-site")];
        match bind {
            BindAddress::Tcp { exposure, .. } => {
                exec.push("--tcp ${JURISEARCH_SITE_BIND}".to_owned());
                if matches!(
                    exposure,
                    TcpExposure::TrustedLan | TcpExposure::Wildcard | TcpExposure::Public
                ) {
                    exec.push("--allow-lan".to_owned());
                }
                if matches!(exposure, TcpExposure::Wildcard) {
                    exec.push("--allow-wildcard-lan".to_owned());
                }
            }
            BindAddress::Unix { .. } => {
                exec.push("--socket ${JURISEARCH_SITE_BIND}".to_owned());
            }
        }
        exec.push("--db-host ${JURISEARCH_DB_HOST}".to_owned());
        exec.push("--db-port ${JURISEARCH_DB_PORT}".to_owned());
        exec.push("--db-name ${JURISEARCH_DB_NAME}".to_owned());
        exec.push("--db-user ${JURISEARCH_READ_USER}".to_owned());
        exec.push("--workers ${JURISEARCH_SITE_WORKERS}".to_owned());
        let exec_start = format!("ExecStart={}", exec.join(" \\\n  "));

        format!(
            "{header}\n\
             # JuriSearch site query service (read-only; versioned site protocol).\n\
             [Unit]\n\
             Description=JuriSearch site query service (read-only; versioned site protocol)\n\
             Documentation=https://github.com/pnocera/jurisearch\n\
             After=network-online.target postgresql.service jurisearch-bge-m3.service\n\
             Wants=network-online.target jurisearch-bge-m3.service\n\
             \n\
             [Service]\n\
             Type=simple\n\
             User={user}\n\
             Group={group}\n\
             EnvironmentFile={env_file}\n\
             {exec_start}\n\
             Restart=on-failure\n\
             RestartSec=5\n\
             KillSignal=SIGTERM\n\
             TimeoutStopSec=30\n\
             NoNewPrivileges=true\n\
             ProtectSystem=strict\n\
             ProtectHome=true\n\
             PrivateTmp=true\n\
             RuntimeDirectory=jurisearch\n\
             \n\
             [Install]\n\
             WantedBy=multi-user.target\n",
            header = GENERATED_HEADER,
            user = self.system.service_user,
            group = self.system.service_group,
            env_file = self.env_file_path("site.env"),
            exec_start = exec_start,
        )
    }

    fn render_syncd_unit(&self) -> String {
        let syncd_bin = self
            .system
            .install_dir
            .join("jurisearch-syncd")
            .display()
            .to_string();
        let mut exec = vec![syncd_bin];
        exec.push("--server-host ${JURISEARCH_DB_HOST}".to_owned());
        exec.push("--server-port ${JURISEARCH_DB_PORT}".to_owned());
        exec.push("--server-db ${JURISEARCH_DB_NAME}".to_owned());
        exec.push("--writer-user ${JURISEARCH_WRITER_USER}".to_owned());
        exec.push("--read-role ${JURISEARCH_READ_USER}".to_owned());
        exec.push("--owner-role ${JURISEARCH_OWNER_ROLE}".to_owned());
        exec.push("run".to_owned());
        // Corpora are inlined (deterministic from config): systemd `${VAR}` word-splitting cannot
        // interleave a repeated `--corpus` flag reliably.
        for corpus in &self.sync.corpora {
            exec.push(format!("--corpus {corpus}"));
        }
        exec.push("--source-root ${JURISEARCH_SOURCE_ROOT}".to_owned());
        exec.push("--interval-secs ${JURISEARCH_INTERVAL_SECS}".to_owned());
        let exec_start = format!("ExecStart={}", exec.join(" \\\n  "));

        // ReadOnlyPaths is an absolute literal (systemd does NOT expand env vars here).
        let read_only = self.sync.source_root.display().to_string();

        format!(
            "{header}\n\
             # JuriSearch syncd (consumer corpus sync daemon).\n\
             [Unit]\n\
             Description=JuriSearch syncd (consumer corpus sync daemon)\n\
             Documentation=https://github.com/pnocera/jurisearch\n\
             After=network-online.target postgresql.service\n\
             Wants=network-online.target\n\
             \n\
             [Service]\n\
             Type=simple\n\
             User={user}\n\
             Group={group}\n\
             EnvironmentFile={env_file}\n\
             {exec_start}\n\
             KillSignal=SIGTERM\n\
             TimeoutStopSec=120\n\
             Restart=on-failure\n\
             RestartSec=10\n\
             NoNewPrivileges=true\n\
             ProtectSystem=strict\n\
             ProtectHome=true\n\
             PrivateTmp=true\n\
             ReadOnlyPaths={read_only}\n\
             \n\
             [Install]\n\
             WantedBy=multi-user.target\n",
            header = GENERATED_HEADER,
            user = self.system.service_user,
            group = self.system.service_group,
            env_file = self.env_file_path("syncd.env"),
            exec_start = exec_start,
            read_only = read_only,
        )
    }

    fn render_bge_m3_unit(&self) -> String {
        // The llama-server binary path is an absolute literal (ExecStart binary; no env expansion).
        let llama = self.embedder.llama_server.display().to_string();
        let exec = [
            llama,
            "--model ${JURISEARCH_BGE_M3_MODEL}".to_owned(),
            "--embeddings".to_owned(),
            "--pooling ${JURISEARCH_BGE_M3_POOLING}".to_owned(),
            "--host 127.0.0.1".to_owned(),
            "--port ${JURISEARCH_BGE_M3_PORT}".to_owned(),
        ];
        let exec_start = format!("ExecStart={}", exec.join(" \\\n  "));

        format!(
            "{header}\n\
             # JuriSearch local embedding endpoint (bge-m3 via llama.cpp).\n\
             [Unit]\n\
             Description=JuriSearch local embedding endpoint (bge-m3 via llama.cpp)\n\
             Documentation=https://github.com/pnocera/jurisearch\n\
             After=network-online.target\n\
             Wants=network-online.target\n\
             \n\
             [Service]\n\
             Type=simple\n\
             User={user}\n\
             Group={group}\n\
             EnvironmentFile={env_file}\n\
             {exec_start}\n\
             Restart=on-failure\n\
             RestartSec=5\n\
             NoNewPrivileges=true\n\
             ProtectSystem=strict\n\
             ProtectHome=true\n\
             PrivateTmp=true\n\
             \n\
             [Install]\n\
             WantedBy=multi-user.target\n",
            header = GENERATED_HEADER,
            user = self.system.service_user,
            group = self.system.service_group,
            env_file = self.env_file_path("bge-m3.env"),
            exec_start = exec_start,
        )
    }
}

fn push_env(out: &mut String, key: &str, value: &str) {
    out.push_str(key);
    out.push('=');
    out.push_str(value);
    out.push('\n');
}

fn provider_str(provider: EmbeddingProvider) -> &'static str {
    match provider {
        EmbeddingProvider::OpenAiCompatible => "openai_compatible",
        EmbeddingProvider::InProcess => "in_process",
    }
}
