/**
 * Build-id stamp generator (single source of truth for the dashboard's `--version`).
 *
 * Generates `server/buildinfo.ts` with the three values the `--version` contract needs, so the
 * compiled binary prints EXACTLY (matching dist.sh:274-293 / deploy.sh:165-170,:502-507):
 *
 *   jurisearch-dashboard <VERSION> (<COMMIT>, <TARGET>)
 *
 * Resolution (mirrors crates/jurisearch-buildinfo + dist.sh:253-262):
 *   VERSION = root Cargo.toml [workspace.package] version  (never hardcoded — single source of truth)
 *   COMMIT  = see resolveCommit() — graceful precedence identical to the Rust/release path
 *   TARGET  = x86_64-unknown-linux-gnu  (the bun-linux-x64 compile target's GNU triple = dist.sh $TARGET)
 *
 * The IO is a thin shell (`stamp()` + the `import.meta.main` block); the contract logic lives in pure,
 * unit-tested helpers below (see scripts/stamp.test.ts).
 */
import { resolve } from "node:path";
import { formatVersionLine } from "../server/version";

export const BUILD_TARGET = "x86_64-unknown-linux-gnu";

export const scriptDir = import.meta.dir;
export const dashboardRoot = resolve(scriptDir, "..");
export const repoRoot = resolve(dashboardRoot, "..", "..");
export const cargoTomlPath = resolve(repoRoot, "Cargo.toml");
export const buildInfoPath = resolve(dashboardRoot, "server", "buildinfo.ts");

/** Parse `[workspace.package] version` from a Cargo.toml string. Pure. */
export function parseWorkspaceVersion(cargoToml: string): string {
  const section = cargoToml.match(/\[workspace\.package\]([\s\S]*?)(?:\n\[|$)/);
  if (!section?.[1]) {
    throw new Error("stamp: no [workspace.package] section in Cargo.toml");
  }
  const version = section[1].match(/^\s*version\s*=\s*"([^"]+)"/m);
  if (!version?.[1]) {
    throw new Error("stamp: no version in [workspace.package] of Cargo.toml");
  }
  return version[1];
}

export interface CommitSources {
  /** $JURISEARCH_BUILD_COMMIT (the dist.sh override). */
  override: string | undefined;
  /** `git rev-parse --short=12 HEAD`, or null on any failure. */
  gitShort: () => string | null;
  /** `git rev-parse HEAD`, or null on any failure. */
  gitFull: () => string | null;
}

/**
 * Commit-resolution precedence, faithful to dist.sh:253-262 + crates/jurisearch-buildinfo/src/lib.rs:96-115
 * (degrade gracefully — NEVER throw, so no-git / source-tarball builds still stamp):
 *   1. non-empty JURISEARCH_BUILD_COMMIT (the reproducible-release override)
 *   2. `git rev-parse --short=12 HEAD`
 *   3. full `git rev-parse HEAD` truncated to 12
 *   4. "unknown"
 * Pure (git access is injected) → unit-tested.
 */
export function resolveCommit(sources: CommitSources): string {
  const override = sources.override?.trim();
  if (override) {
    return override;
  }
  const short = sources.gitShort()?.trim();
  if (short) {
    return short;
  }
  const full = sources.gitFull()?.trim();
  if (full) {
    return full.slice(0, 12);
  }
  return "unknown";
}

/** Render the generated `server/buildinfo.ts` contents. Pure. */
export function renderBuildInfo(info: { version: string; commit: string; target: string }): string {
  return `// GENERATED by scripts/stamp.ts — DO NOT EDIT.
// Regenerated on every \`bun run stamp|typecheck|test|compile\`. Gitignored.
export const BUILD_VERSION = ${JSON.stringify(info.version)};
export const BUILD_COMMIT = ${JSON.stringify(info.commit)};
export const BUILD_TARGET = ${JSON.stringify(info.target)};
`;
}

/** Run `git -C <repoRoot> <args>`; trimmed stdout, or null on any failure (missing git / non-zero). */
export function gitOutput(args: string[]): string | null {
  const r = Bun.spawnSync(["git", "-C", repoRoot, ...args]);
  if (!r.success) {
    return null;
  }
  const out = r.stdout.toString().trim();
  return out.length > 0 ? out : null;
}

/** IO shell: resolve version + commit + target, write `server/buildinfo.ts`. */
export async function stamp(): Promise<{ version: string; commit: string; target: string }> {
  const version = parseWorkspaceVersion(await Bun.file(cargoTomlPath).text());
  const commit = resolveCommit({
    override: process.env.JURISEARCH_BUILD_COMMIT,
    gitShort: () => gitOutput(["rev-parse", "--short=12", "HEAD"]),
    gitFull: () => gitOutput(["rev-parse", "HEAD"]),
  });
  const target = BUILD_TARGET;
  await Bun.write(buildInfoPath, renderBuildInfo({ version, commit, target }));
  return { version, commit, target };
}

if (import.meta.main) {
  const { version, commit, target } = await stamp();
  console.log(`stamp: ${buildInfoPath} -> ${formatVersionLine(version, commit, target)}`);
}
