//! The tiny SIGNED FIXTURE corpus for CI/demo smoke (plan `00` resolved decision #10, M5-B).
//!
//! This module owns the FIXTURE CONTRACT: a small set of DOCUMENTED, STABLE constants — the corpus name,
//! the stable fixture document id, a query term known to retrieve it, and a guaranteed-absent id for the
//! negative leg — that BOTH `demo smoke` AND `site smoke --fetch-id` reuse, so the smoke legs reference
//! ONE source of truth and a runbook can pin exact values.
//!
//! Per decision #10 the CI/demo path uses this fixture; OPERATED single-host acceptance uses a REAL DILA
//! document id after the producer has published real packages. The static fixture ARTIFACT (a tiny signed
//! baseline package + signed remote manifest) lives under `crates/jurisearch-deploy/fixtures/` so CI does
//! not need a live DB to RUN the smoke decision logic; the artifact is (re)generated by
//! [`generate_fixture`], which drives the REAL `jurisearch-package-build` library APIs against a populated
//! producer database (an authorized-only step — see the fixtures README).

use std::path::{Path, PathBuf};

use jurisearch_package::Signer;
use jurisearch_package_build::BuildError;
use jurisearch_package_build::{
    BaselineParams, RemoteManifestParams, build_baseline, build_remote_manifest, publish_package,
    publish_remote_manifest, published_manifest_path,
};
use jurisearch_storage::backend::DbClientSource;

use crate::config::SiteConfig;
use crate::error::{DeployError, ValidationErrors};

use super::smoke::SmokePlan;

/// The fixture package corpus (the single v1 `core` corpus — see plan invariants).
pub const FIXTURE_CORPUS: &str = "core";

/// The DOCUMENTED, STABLE fixture document id. Reused verbatim by `demo smoke` and as the default
/// `--fetch-id` for `site smoke` against the demo fixture. It is a synthetic but well-formed DILA-shaped
/// jurisprudence id reserved for the fixture ONLY — operated acceptance uses a real published id instead.
pub const FIXTURE_DOC_ID: &str = "cass:FIXTURE-0000000001";

/// A query term present in the fixture document, expected to retrieve [`FIXTURE_DOC_ID`] via BM25 (and
/// via hybrid when the loopback embedder is available).
pub const FIXTURE_QUERY_TERM: &str = "responsabilite";

/// A guaranteed-ABSENT id for the negative not-found smoke leg (never minted by the fixture generator).
pub const FIXTURE_MISSING_ID: &str = "cass:FIXTURE-DOES-NOT-EXIST";

/// The repo-relative path where the static signed fixture artifact (baseline package + remote manifest)
/// is published for CI/demo, under the deterministic `published_root/<corpus>/...` layout.
pub const FIXTURE_RELATIVE_ROOT: &str = "crates/jurisearch-deploy/fixtures/published";

/// The smoke plan for the FIXTURE corpus, with the HYBRID leg ENABLED (the demo/site has a loopback
/// query embedder + model/tokenizer assets present).
#[must_use]
pub fn fixture_smoke_plan_with_hybrid() -> SmokePlan {
    SmokePlan::with_hybrid(FIXTURE_DOC_ID, FIXTURE_QUERY_TERM, FIXTURE_MISSING_ID)
}

/// The smoke plan for the FIXTURE corpus with the HYBRID leg recorded as a skip carrying `reason` (used
/// when model/tokenizer assets are absent — an explicit recorded skip, never a silent one).
#[must_use]
pub fn fixture_smoke_plan_without_hybrid(reason: impl Into<String>) -> SmokePlan {
    SmokePlan::without_hybrid(
        FIXTURE_DOC_ID,
        FIXTURE_QUERY_TERM,
        FIXTURE_MISSING_ID,
        reason,
    )
}

/// PREFLIGHT GUARD: every configured corpus must have a published signed remote manifest under
/// `sync.source_root` (`<source_root>/<corpus>/manifest.json`) BEFORE a fixture-backed `demo up`/`demo
/// smoke`/catch-up proceeds. The committed fixture bytes are an AUTHORIZED-ONLY generation step (they
/// require a populated producer DB — see the fixtures README); when they are absent this turns the
/// otherwise-obscure downstream catch-up/readiness failure into ONE clear, actionable diagnostic that
/// names the exact missing path and the documented generator. Fail-fast, never a generic readiness error.
///
/// # Errors
/// [`DeployError::Validation`] listing each corpus whose published manifest is missing.
pub fn ensure_published_artifacts(config: &SiteConfig) -> Result<(), DeployError> {
    let mut errors = ValidationErrors::default();
    for corpus in &config.sync.corpora {
        let manifest = published_manifest_path(&config.sync.source_root, corpus);
        if !manifest.exists() {
            errors.push(
                "fixture.published_missing",
                format!(
                    "published fixture artifact missing: expected `{}` for corpus `{corpus}` under \
                     sync.source_root `{}`",
                    manifest.display(),
                    config.sync.source_root.display()
                ),
                "the committed fixture bytes are an authorized-only generation step — run the documented \
                 generator `jurisearch_deploy::ops::fixture::generate_fixture` against a populated \
                 producer DB (see crates/jurisearch-deploy/fixtures/README.md), then commit the \
                 published/ tree; the live fixture demo is UNAVAILABLE until then",
            );
        }
    }
    errors.into_result().map_err(DeployError::Validation)
}

/// What [`generate_fixture`] produced — the published root + the signed remote-manifest path.
#[derive(Debug, Clone)]
pub struct FixtureArtifacts {
    pub corpus: String,
    pub package_id: String,
    pub published_root: PathBuf,
    pub manifest_path: PathBuf,
    pub total_rows: u64,
}

/// (Re)generate the static fixture artifact via the REAL `jurisearch-package-build` library APIs:
/// `build_baseline` → `publish_package` → `build_remote_manifest` → `publish_remote_manifest`, producing
/// the deterministic `published_root/<corpus>/{manifest.json, packages/...}` layout the site's
/// `DirectoryCatchupSource` consumes.
///
/// This is the DOCUMENTED GENERATOR HELPER. It requires a PRODUCER database (`producer`) already
/// populated with the fixture document (id [`FIXTURE_DOC_ID`]) and a real [`Signer`] — i.e. it is an
/// authorized-only step that needs live infra. CI does NOT call this; CI consumes the committed static
/// artifact under [`FIXTURE_RELATIVE_ROOT`] and unit-tests the smoke/watchdog DECISION logic without a DB.
///
/// # Errors
/// [`BuildError`] if the baseline build, publish, manifest build, or manifest publish fails.
pub fn generate_fixture(
    producer: &impl DbClientSource,
    signer: &dyn Signer,
    published_root: &Path,
    build_scratch_dir: &Path,
    baseline: &BaselineParams,
    remote: &RemoteManifestParams,
) -> Result<FixtureArtifacts, BuildError> {
    // 1. Build the signed baseline artifact into a scratch dir (per-table COPY payload + signed manifest).
    let report = build_baseline(
        producer,
        FIXTURE_CORPUS,
        build_scratch_dir,
        signer,
        baseline,
    )?;
    // 2. Publish it under the deterministic served root (atomic stage+rename, immutable package id).
    publish_package(
        published_root,
        FIXTURE_CORPUS,
        &report.package_id,
        build_scratch_dir,
    )?;
    // 3. Build + 4. publish the signed per-corpus remote manifest (head/active-baseline binding).
    let manifest = build_remote_manifest(producer, FIXTURE_CORPUS, published_root, signer, remote)?;
    publish_remote_manifest(published_root, FIXTURE_CORPUS, &manifest)?;

    Ok(FixtureArtifacts {
        corpus: FIXTURE_CORPUS.to_owned(),
        package_id: report.package_id,
        published_root: published_root.to_owned(),
        manifest_path: published_manifest_path(published_root, FIXTURE_CORPUS),
        total_rows: report.total_rows,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_stable_fixture_constants_are_documented_and_distinct() {
        // The known id and the negative id MUST differ (the negative leg relies on the latter's absence).
        assert_ne!(FIXTURE_DOC_ID, FIXTURE_MISSING_ID);
        assert_eq!(FIXTURE_CORPUS, "core");
        assert!(!FIXTURE_DOC_ID.is_empty());
        assert!(!FIXTURE_QUERY_TERM.is_empty());
    }

    #[test]
    fn the_fixture_plan_threads_the_stable_constants_into_the_smoke_legs() {
        let plan = fixture_smoke_plan_with_hybrid();
        assert_eq!(plan.known_id, FIXTURE_DOC_ID);
        assert_eq!(plan.query_term, FIXTURE_QUERY_TERM);
        assert_eq!(plan.missing_id, FIXTURE_MISSING_ID);
        assert!(plan.hybrid_enabled);
    }

    #[test]
    fn the_no_hybrid_fixture_plan_records_an_explicit_reason() {
        let plan = fixture_smoke_plan_without_hybrid("model/tokenizer assets absent");
        assert!(!plan.hybrid_enabled);
        assert_eq!(plan.hybrid_skip_reason, "model/tokenizer assets absent");
    }

    #[test]
    fn the_preflight_guard_fails_fast_when_the_published_manifest_is_absent() {
        use crate::config::SITE_CONFIG_EXAMPLE;

        let mut config =
            SiteConfig::parse_str(SITE_CONFIG_EXAMPLE, Path::new("site.toml")).unwrap();
        let root = std::env::temp_dir().join(format!(
            "jurisearch-fixture-guard-{}-{:?}",
            std::process::id(),
            std::thread::current().id()
        ));
        let _ = std::fs::remove_dir_all(&root);
        config.sync.source_root = root.clone();
        config.sync.corpora = vec![FIXTURE_CORPUS.to_owned()];

        // Absent → fail fast (not a generic readiness failure), with the missing path + generator named.
        let err = ensure_published_artifacts(&config).expect_err("missing artifact must fail fast");
        let rendered = err.to_string();
        assert!(rendered.contains("manifest.json"), "names the missing path");
        assert!(rendered.contains("generate_fixture"), "names the generator");

        // Generate the manifest → the guard passes.
        let manifest = published_manifest_path(&root, FIXTURE_CORPUS);
        std::fs::create_dir_all(manifest.parent().unwrap()).unwrap();
        std::fs::write(&manifest, b"{}").unwrap();
        assert!(ensure_published_artifacts(&config).is_ok());

        let _ = std::fs::remove_dir_all(&root);
    }
}
